[package]
name = "uqoin-client"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
finitelib = { version = "0.1.11", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uqoin-core = { path = "../uqoin-core" }
